INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'Tiger King', 1, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'McDonald''s', 2, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'MacBook PRO', 3, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'D&D Player''s Handbook', 4, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'Pokémon', 5, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'Game of Thrones', 1, 2);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (1, 'midterm project', 4, 3);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'Tiger King', 1, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'McDonald''s', 2, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'MacBook PRO', 3, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'D&D Player''s Handbook', 4, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'Pokémon', 5, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'Game of Thrones', 1, 2);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (2, 'midterm project', 4, 3);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'Tiger King', 1, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'McDonald''s', 2, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'MacBook PRO', 3, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'D&D Player''s Handbook', 4, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'Pokémon', 5, 1);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'Game of Thrones', 1, 2);
INSERT INTO to_dos (user_id, name, category_id, status_id) VALUES (3, 'midterm project', 4, 3);
