DROP TABLE IF EXISTS items CASCADE;
CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER REFERENCES users_id ON DELETE CASCADE,
  name VARCHAR(255),
  category INTEGER REFERENCES categories(id) ON DELETE CASCADE
);
